name: build_and_test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Install Module
      run: sudo apt install libwayland-client0 libwayland-dev libxkbcommon-dev vulkan-tools libvulkan-dev libx11-dev libegl1-mesa-dev libegl1-mesa-dev libwayland-egl1-mesa-dev libwayland-client0 libwayland-dev libwayland-cursor0 libwayland-cursor-dev libxkbcommon-dev libxkbcommon-x11-dev libx11-xcb-dev libxcursor-dev libxfixes-dev && go mod tidy

    - name: Test
      run: go test -coverprofile=coverage.txt

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
